parameters:
#    eticsol.example.class: Eticsol\EticsolBundle\Example

services:
#    eticsol.example:
#        class: %eticsol.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


 factura.buscador:
     class: Eticsol\EticsolBundle\Services\BuscadorFactura
     arguments: [@doctrine.orm.entity_manager]