security:
    encoders:
       FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/factura , roles: ROLE_SUPER_ADMIN }
        - { path: ^/iva , roles: ROLE_SUPER_ADMIN }
        - { path: ^/provincia , roles: ROLE_SUPER_ADMIN }
        - { path: ^/localidad , roles: ROLE_SUPER_ADMIN }
        - { path: ^/producto , roles: ROLE_SUPER_ADMIN }
        - { path: ^/proveedor , roles: ROLE_SUPER_ADMIN }
        
        
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

       #-------------------------------------------------------------------------------
